name: Deploy of server #nombre del workflow

on:
  push:
    branches: [ master ]

jobs:
  first_job:
    runs-on: ubuntu-latest   # ruunners en que sistema operativo de la maquina virutal se correra

    steps:									#tareas a realizar que estan en los job 
      - name: erika valencia
        run: echo "hola erika valencia"


  secund_job:
   needs: first_job         # indica que depende de otro job en este caso first_job, lo cual indica que se ejecutar despues de finalizada su dependencia
   runs-on: ubuntu-latest

   steps:
    - name: paula  valencia
      run: echo "hola Paula valencia"
