name: Deploy of server #nombre del workflow

on:
  push:
    branches: [ master ]

jobs:
  first_job:
    name: Tutorial codigo facilito
    runs-on: ubuntu-latest   # ruunners en que sistema operativo de la maquina virutal se correra

    steps:									#tareas a realizar que estan en los job 
      - name: Working dir
        id: step_1  # para poder usar la informacin de otros step, debemos hacerlo creando un id al step
        run: echo "my_variable=hola mundo" >>  $GITHUB_OUTPUT

      - name: obtener mensaje 
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  secund_job:
   needs: first_job         # indica que depende de otro job en este caso first_job, lo cual indica que se ejecutar despues de finalizada su dependencia
   runs-on: ubuntu-latest

   steps:
    - name: paula  valencia
      run: echo "hola Paula valencia ${{github.ref}}"
